#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

fail() {
  echo "release-check: $*" >&2
  exit 1
}

require_file() {
  local path="$1"
  [[ -f "$path" ]] || fail "missing required file: $path"
}

require_file "VERSION"
require_file "CHANGELOG.md"
require_file "README.md"
require_file "package.json"
require_file "docs/INSTALL.md"
require_file "docs/DISCOVERY.md"
require_file "docs/FAQ.md"
require_file "docs/QUICKSTART.md"
require_file "docs/USAGE.md"
require_file "scripts/install.sh"
require_file "scripts/install.js"
require_file "scripts/install.ps1"
require_file "scripts/install-openclaw.ps1"
require_file "scripts/install-openclaw.sh"
require_file "scripts/run.js"
require_file "scripts/quality-gates.sh"
require_file "scripts/run-golangci-lint.sh"
require_file "scripts/generate-homebrew-formula.sh"
require_file "skills/md2wechat/SKILL.md"
require_file "platforms/openclaw/md2wechat/SKILL.md"
require_file ".github/workflows/release.yml"
require_file ".github/workflows/ci.yml"
require_file "AGENTS.md"
require_file "docs/OPENCLAW.md"
require_file ".claude-plugin/marketplace.json"

version="$(tr -d '[:space:]' < VERSION)"
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "VERSION must be SemVer, got: $version"

changelog_version="$(sed -n 's/^## \[\([0-9][^]]*\)\].*/\1/p' CHANGELOG.md | head -n1)"
[[ -n "$changelog_version" ]] || fail "failed to read top CHANGELOG version"
[[ "$changelog_version" == "$version" ]] || fail "VERSION ($version) does not match CHANGELOG top version ($changelog_version)"

marketplace_version="$(sed -n 's/.*"version": "\([0-9][^"]*\)".*/\1/p' .claude-plugin/marketplace.json | head -n1)"
[[ -n "$marketplace_version" ]] || fail "failed to read marketplace plugin version"
[[ "$marketplace_version" == "$version" ]] || fail "VERSION ($version) does not match marketplace version ($marketplace_version)"

package_version="$(node -p "require('./package.json').version")"
[[ -n "$package_version" ]] || fail "failed to read package.json version"
[[ "$package_version" == "$version" ]] || fail "VERSION ($version) does not match package.json version ($package_version)"

package_name="$(node -p "require('./package.json').name")"
[[ "$package_name" == "@geekjourneyx/md2wechat" ]] || fail "package.json name must stay @geekjourneyx/md2wechat"

if ! node -e "const pkg=require('./package.json'); if ('os' in pkg || 'cpu' in pkg) process.exit(1)"; then
  fail "package.json must not claim a global os/cpu matrix; scripts/install.js is the source of truth for supported npm targets"
fi

grep -q 'MD2WECHAT_VERSION' scripts/install.sh || fail "scripts/install.sh must support MD2WECHAT_VERSION"
grep -q 'MD2WECHAT_RELEASE_BASE_URL' scripts/install.sh || fail "scripts/install.sh must support MD2WECHAT_RELEASE_BASE_URL"
grep -q 'MD2WECHAT_INSTALL_DIR' scripts/install.sh || fail "scripts/install.sh must support MD2WECHAT_INSTALL_DIR"
grep -q 'MD2WECHAT_RELEASE_BASE_URL' scripts/install.js || fail "scripts/install.js must support MD2WECHAT_RELEASE_BASE_URL"
grep -q 'checksums.txt' scripts/install.js || fail "scripts/install.js must verify checksums.txt"
grep -q 'npm install -g @geekjourneyx/md2wechat' scripts/run.js || fail "scripts/run.js must point users at the npm install command"
grep -q 'MD2WECHAT_VERSION' scripts/install.ps1 || fail "scripts/install.ps1 must support MD2WECHAT_VERSION"
grep -q 'MD2WECHAT_RELEASE_BASE_URL' scripts/install.ps1 || fail "scripts/install.ps1 must support MD2WECHAT_RELEASE_BASE_URL"
grep -q 'MD2WECHAT_INSTALL_DIR' scripts/install.ps1 || fail "scripts/install.ps1 must support MD2WECHAT_INSTALL_DIR"
grep -q 'MD2WECHAT_NONINTERACTIVE' scripts/install.ps1 || fail "scripts/install.ps1 must support MD2WECHAT_NONINTERACTIVE"
grep -q 'MD2WECHAT_NO_PATH_UPDATE' scripts/install.ps1 || fail "scripts/install.ps1 must support MD2WECHAT_NO_PATH_UPDATE"
grep -q 'MD2WECHAT_RELEASE_BASE_URL' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must support MD2WECHAT_RELEASE_BASE_URL"
grep -q 'MD2WECHAT_VERSION' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must support MD2WECHAT_VERSION"
grep -q 'MD2WECHAT_INSTALL_DIR' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must support MD2WECHAT_INSTALL_DIR"
grep -q 'MD2WECHAT_OPENCLAW_INSTALL_DIR' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must support MD2WECHAT_OPENCLAW_INSTALL_DIR"
grep -q 'MD2WECHAT_NONINTERACTIVE' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must support MD2WECHAT_NONINTERACTIVE"
grep -q 'MD2WECHAT_NO_PATH_UPDATE' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must support MD2WECHAT_NO_PATH_UPDATE"
grep -q 'MD2WECHAT_RELEASE_BASE_URL' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must support MD2WECHAT_RELEASE_BASE_URL"
grep -q 'MD2WECHAT_VERSION' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must support MD2WECHAT_VERSION"
grep -q 'MD2WECHAT_OPENCLAW_INSTALL_DIR' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must support MD2WECHAT_OPENCLAW_INSTALL_DIR"
grep -q 'MD2WECHAT_INSTALL_DIR' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must support MD2WECHAT_INSTALL_DIR"
grep -q 'MD2WECHAT_NONINTERACTIVE' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must support MD2WECHAT_NONINTERACTIVE"
! grep -q 'releases/latest/download' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must not silently fall back to releases/latest/download"
grep -q 'checksums.txt' scripts/install.sh || fail "scripts/install.sh must verify checksums.txt"
grep -q 'checksums.txt' scripts/install.ps1 || fail "scripts/install.ps1 must verify checksums.txt"
grep -q 'checksums.txt' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must verify checksums.txt"
grep -q 'checksums.txt' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must verify checksums.txt"
grep -q 'md2wechat-openclaw-skill.tar.gz' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must install the OpenClaw release archive"
grep -q 'md2wechat-openclaw-skill.tar.gz' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must install the OpenClaw release archive"
grep -q 'md2wechat-linux-amd64' scripts/install-openclaw.sh || fail "scripts/install-openclaw.sh must install a versioned md2wechat CLI"
grep -q 'md2wechat-windows-amd64.exe' scripts/install-openclaw.ps1 || fail "scripts/install-openclaw.ps1 must install a versioned md2wechat CLI"
grep -q 'upload-artifact' .github/workflows/release.yml || fail "release workflow must upload a release artifact"
grep -q 'download-artifact' .github/workflows/release.yml || fail "release workflow must download a release artifact"
grep -q 'npm pack' .github/workflows/release.yml || fail "release workflow must smoke the npm package"
grep -q 'npm install -g' .github/workflows/release.yml || fail "release workflow must smoke npm global install"
grep -q 'npm publish --access public' .github/workflows/release.yml || fail "release workflow must publish the npm package"
grep -q 'NPM_TOKEN' .github/workflows/release.yml || fail "release workflow must require NPM_TOKEN for npm publish"
grep -q 'install.sh' .github/workflows/release.yml || fail "release workflow must publish install.sh"
grep -q 'install.ps1' .github/workflows/release.yml || fail "release workflow must publish install.ps1"
grep -q 'install-openclaw.ps1' .github/workflows/release.yml || fail "release workflow must publish install-openclaw.ps1"
grep -q 'install-openclaw.sh' .github/workflows/release.yml || fail "release workflow must publish install-openclaw.sh"
grep -q 'md2wechat-openclaw-skill.tar.gz' .github/workflows/release.yml || fail "release workflow must publish the OpenClaw skill archive"
grep -q 'md2wechat_Darwin_arm64.tar.gz' .github/workflows/release.yml || fail "release workflow must publish the macOS arm64 Homebrew archive"
grep -q 'md2wechat_Darwin_x86_64.tar.gz' .github/workflows/release.yml || fail "release workflow must publish the macOS x86_64 Homebrew archive"
grep -q 'md2wechat_Linux_arm64.tar.gz' .github/workflows/release.yml || fail "release workflow must publish the Linux arm64 Homebrew archive"
grep -q 'md2wechat_Linux_x86_64.tar.gz' .github/workflows/release.yml || fail "release workflow must publish the Linux x86_64 Homebrew archive"
grep -q 'platforms/openclaw/md2wechat' .github/workflows/release.yml || fail "release workflow must package the OpenClaw-specific skill"
grep -q 'version --json' .github/workflows/release.yml || fail "release workflow must smoke version --json"
grep -q 'MD2WECHAT_RELEASE_BASE_URL' .github/workflows/release.yml || fail "release workflow must smoke the installers from the same bundle"
grep -q 'HOMEBREW_TAP_GITHUB_TOKEN' .github/workflows/release.yml || fail "release workflow must update the tap repository with HOMEBREW_TAP_GITHUB_TOKEN"
grep -q 'generate-homebrew-formula.sh' .github/workflows/release.yml || fail "release workflow must generate the Homebrew formula via scripts/generate-homebrew-formula.sh"
grep -q '"install"' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill metadata must declare install resources"
grep -q '"clawdbot"' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill metadata must use metadata.clawdbot"
grep -q '"bins":\["md2wechat"\]' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill metadata must declare md2wechat as a required bin"
grep -q '"formula":"geekjourneyx/tap/md2wechat"' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill metadata must declare the brew install path"
grep -q '"module":"github.com/geekjourneyx/md2wechat-skill/cmd/md2wechat@latest"' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill metadata must declare the go install path"
grep -q 'releases/download/v' README.md || fail "README must point install instructions at fixed-version release assets"
grep -q 'releases/download/v' docs/INSTALL.md || fail "docs/INSTALL.md must point install instructions at fixed-version release assets"
grep -q 'releases/download/v' docs/OPENCLAW.md || fail "docs/OPENCLAW.md must point OpenClaw install instructions at fixed-version release assets"
grep -q 'npm install -g @geekjourneyx/md2wechat' README.md || fail "README must document the npm install path"
grep -q 'npm install -g @geekjourneyx/md2wechat' docs/INSTALL.md || fail "docs/INSTALL.md must document the npm install path"
grep -q 'npx cnpm sync @geekjourneyx/md2wechat' docs/INSTALL.md || fail "docs/INSTALL.md must document the post-publish npmmirror sync step"
grep -q 'npx cnpm sync @geekjourneyx/md2wechat' docs/FAQ.md || fail "docs/FAQ.md must document the npmmirror sync recovery path"
grep -q 'brew install geekjourneyx/tap/md2wechat' README.md || fail "README must document the tap install path"
grep -q 'brew install geekjourneyx/tap/md2wechat' docs/INSTALL.md || fail "docs/INSTALL.md must document the tap install path"
! grep -q 'raw.githubusercontent.com/geekjourneyx/md2wechat-skill/main/scripts/install.sh' README.md || fail "README must not point the md2wechat installer at main"
! grep -q 'raw.githubusercontent.com/geekjourneyx/md2wechat-skill/main/scripts/install.ps1' README.md || fail "README must not point the md2wechat installer at main"
! grep -q 'raw.githubusercontent.com/geekjourneyx/md2wechat-skill/main/scripts/install-openclaw.sh' README.md || fail "README must not point the OpenClaw installer at main"
! grep -q 'raw.githubusercontent.com/geekjourneyx/md2wechat-skill/main/scripts/install.sh' docs/INSTALL.md || fail "docs/INSTALL.md must not point the md2wechat installer at main"
! grep -q 'raw.githubusercontent.com/geekjourneyx/md2wechat-skill/main/scripts/install.ps1' docs/INSTALL.md || fail "docs/INSTALL.md must not point the md2wechat installer at main"
! grep -q 'raw.githubusercontent.com/geekjourneyx/md2wechat-skill/main/scripts/install-openclaw.sh' docs/OPENCLAW.md || fail "docs/OPENCLAW.md must not point the OpenClaw installer at main"
grep -q 'md2wechat inspect article.md' README.md || fail "README must document inspect as part of the confirm-first flow"
grep -q 'md2wechat preview article.md' README.md || fail "README must document preview as part of the confirm-first flow"
grep -q 'md2wechat inspect article.md' docs/QUICKSTART.md || fail "docs/QUICKSTART.md must document inspect"
grep -q 'md2wechat preview article.md' docs/QUICKSTART.md || fail "docs/QUICKSTART.md must document preview"
grep -q 'md2wechat inspect article.md --json' docs/DISCOVERY.md || fail "docs/DISCOVERY.md must document inspect --json"
grep -q 'md2wechat preview article.md --json' docs/DISCOVERY.md || fail "docs/DISCOVERY.md must document preview --json"
grep -q 'md2wechat inspect article.md' docs/FAQ.md || fail "docs/FAQ.md must document inspect"
grep -q 'md2wechat preview article.md' docs/FAQ.md || fail "docs/FAQ.md must document preview"
grep -q 'md2wechat inspect article.md' docs/USAGE.md || fail "docs/USAGE.md must document inspect"
grep -q 'md2wechat preview article.md' docs/USAGE.md || fail "docs/USAGE.md must document preview"
grep -q '`inspect` is the source-of-truth command' skills/md2wechat/SKILL.md || fail "skills/md2wechat/SKILL.md must describe inspect as the source-of-truth command"
grep -q '`preview --mode ai` is degraded confirmation only' skills/md2wechat/SKILL.md || fail "skills/md2wechat/SKILL.md must describe degraded AI preview behavior"
grep -q '`inspect` is the source-of-truth command' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill must describe inspect as the source-of-truth command"
grep -q '`preview --mode ai` is degraded confirmation only' platforms/openclaw/md2wechat/SKILL.md || fail "OpenClaw skill must describe degraded AI preview behavior"
grep -q 'bash scripts/quality-gates.sh' .github/workflows/quality-gates.yml || fail ".github/workflows/quality-gates.yml must use the shared scripts/quality-gates.sh gate"
grep -q 'VERSION' Makefile || fail "Makefile must reference VERSION"
grep -q 'artifact smoke' AGENTS.md || fail "AGENTS.md must mention artifact smoke"

echo "release-check: OK (version $version)"
